#同步作业主程序配置
#mainclass=org.frameworkset.datatran.imp.Db2EleasticsearchDemo
#mainclass=org.frameworkset.datatran.imp.metrics.Elasticsearch2EleasticsearchMetricsDemo
#mainclass=org.frameworkset.datatran.imp.jobflow.JobFlowTxtZipFileDownload
mainclass=org.frameworkset.datatran.feishu.FeishuEmployeeApp
 
elasticsearch.showTemplate=true



# 分析作业的配置
bulkSize=150
workThreads=5
workThreadQueue=100
batchSize=1000
fetchSize=1000
increamentEndOffset=300
#任务延迟执行deylay毫秒后执行
deyLay=1000
period=30000
fileLiveTime=604800000
orderWindowTime=3600
delayedScan=60000
##外部渠道订单配置
channelOrderJob.startChannelOrderTime=20230101

 
#新文件扫描时间间隔，1分钟扫描一次，单位：毫秒
newFileScanInterval = 60000



